### ISSUE TITLE
Decode error when working with firefox headers.

### ISSUE THREAD

**Issue by CrowdHailer** [nesQuick/elixir-hpack#9]
Hi I am experimenting with building an HTTP2 server and am using this repo for header compression. When testing my server with firefox as a client I keep getting the following error.

```
** (FunctionClauseError) no function clause matching in HPack.Huffman.dec/3
    (hpack) lib/hpack/huffman.ex:300: HPack.Huffman.dec(<<1::size(2)>>, 2, "Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0yh/cfxt/html,application/xhtml+xml,application/xml;q=0")
    (hpack) lib/hpack.ex:220: HPack.parse_string/1
    (hpack) lib/hpack.ex:125: HPack.parse/3
    (ace) lib/ace/http2.ex:200: Ace.HTTP2.consume_frame/2
    (ace) lib/ace/http2.ex:149: Ace.HTTP2.consume/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

Obviously the problem is something to do with user agent header, but as of now I havent managed to debug much further

**Comment by nesQuick** [comment]
Hey,

Thanks for the report. Could you please provide a failing test case?

Thanks a bunch!

**Comment by CrowdHailer** [comment]
My mistake, I make some error removing padding or priority. I tried to see if there was anything I could do to improve the error message but no result so far

**Comment by nesQuick** [comment]
Thanks for your feedback. If you ever find a way to improve the error messages please send it along :)
